### ISSUE TITLE
Including hand-made asserts into Assertions and SoftAssertions

### ISSUE THREAD

**Issue by dibog** [joel-costigliola/assertj-assertions-generator-maven-plugin#22]
With the help of the maven plugin I can create Assertions and SoftAssertions for my domain objects.
But for some domain objects I already have created handmae Asserts. Currently the assertThat(*) if have added there won't be included within the generated Assertions and SoftAssertions.

What do I wrong or maybe I haven't really understood the plugin?

Another thing I just wondered:
Why is the generated SoftAssertions not usable as JunitRule. Why not extending it from JUnitSoftAssertions?

**Comment by joel-costigliola** [comment]
@dibog if you are still interested in this issue, can you provide an example of how things should work ?

**Comment by dibog** [comment]
Hi Joel,

I'm now using AssertJ without custom written/generated Assertions. E.g.
taking you Player example:

Instead of PlayerAssert.assertThat(player).hasNoTeams() I'm doing
Assertions.assertThat(player.getTeam()).hasLength(0) or similary.

I checked today your assert-generation again, and I currently have problems
that eclipse doesn't see your generated assertions.
E.g.my test case using your generated code marks an error, while running
maven on the command line works fine.

Best regards,
Dieter


2015-07-25 13:10 GMT+02:00 Joel Costigliola <notifications@github.com>:

**Comment by joel-costigliola** [comment]
You need to set the directory where sources are generated as an eclipse source (project > java build path > Add folder in the `Source` tab. The other solution is to generate the classes directly in a source directory known by eclipse (ex : src/test/java).

if it runs fine from maven command line, then it's just a matter of configuring correctly your eclipse project.

I'm closing this issue as it's not a problem anymore.
