### ISSUE TITLE
Preserving hand-written assertions

### ISSUE THREAD

**Issue by j-maly** [joel-costigliola/assertj-assertions-generator-maven-plugin#25]
Hi, 
if I want to add some assertions of my own (e.g. hasX), how should I do that so that they are not wiped out every time I regenerate the file?

**Comment by joel-costigliola** [comment]
The work to keep manually written assertions requires a huge change in the assertion generator as it was not designed with that purpose in mind. I'm closing this issue for that reason, I like the idea though.
Moreover as custom assertions templates are going to be supported, users will be able to generate richer assertions, it does not completely address this issue but should improve things.
