### ISSUE TITLE
Please add @Generated annotation to generated test assertion classes

### ISSUE THREAD

**Issue by binkley** [joel-costigliola/assertj-assertions-generator-maven-plugin#27]
Kindly add the "@Generated" annotation - [javax.annotation.Generated](https://docs.oracle.com/javase/8/docs/api/javax/annotation/Generated.html).  This helps IDE users recognize that these classes are generated code, and should not be edited.

**Comment by joel-costigliola** [comment]
I will kindly do it by default but if you have the 2.0 version you can can [override templates](http://joel-costigliola.github.io/assertj/assertj-assertions-generator-maven-plugin.html#custom-templates) (custom_assertion_class_template.txt in that case).

**Comment by binkley** [comment]
Thanks, Joel.  I'll update my templates.  It does seem sensible as a default.
