### ISSUE TITLE
Documentation: 'excludes' must not be inside 'packages'

### ISSUE THREAD

**Issue by jesperdj** [joel-costigliola/assertj-assertions-generator-maven-plugin#36]
There is an error in the documentation on this page:
http://joel-costigliola.github.io/assertj/assertj-assertions-generator-maven-plugin.html

Under the heading "Including and excluding classes from assertion generation" there is an example which shows an `<excludes>` element which is nested inside the `<packages>` element.

    <configuration>
        <packages>
            <param>com.google.common.net</param>
            <excludes>
                <param>.*google.*HostSpecifier</param>
                <param>.*google.*Headers</param>
                <param>.*google.*Escaper.*</param>
            </excludes>
        </packages>
    </configuration>

This is incorrect. The `<excludes>` element must not be inside the `<packages>` element.

The example should look like this:

    <configuration>
        <packages>
            <param>com.google.common.net</param>
        </packages>
        <excludes>
            <param>.*google.*HostSpecifier</param>
            <param>.*google.*Headers</param>
            <param>.*google.*Escaper.*</param>
        </excludes>
    </configuration>

**Comment by joel-costigliola** [comment]
Thanks for reporting this !

**Comment by joel-costigliola** [comment]
Fixed
