### ISSUE TITLE
Assertions for classes implementing Comparable

### ISSUE THREAD

**Issue by wildcart** [joel-costigliola/assertj-assertions-generator-maven-plugin#41]
I am new to AssertJ and can't get it to generate some assertions I expect it would.

Specifically, I have a class that implements the Java `Comparable` interface and I try to use the 'isLessThan' type of assertions as shown in the [ComparableAssertionsExamples](https://github.com/joel-costigliola/assertj-examples/blob/master/assertions-examples/src/test/java/org/assertj/examples/ComparableAssertionsExamples.java) example.

The class to be tested:
```
package some.package;
public final class ComparableClass implements Comparable<ComparableClass> {
    private String attribute;
    public ComparableClass(final String attr) { this.attribute = attr; }

    public String getAttribute() { return this.attribute; }
    public void setAttribute(final String attr) { this.attribute = attr; }

    @Override
    public int compareTo(final ComparableClass other) {
        return this.attribute.compareTo(other.getAttribute());
    }   

    @Override
    public String toString() { return attribute; }   
}
```

The test class:
```
package some.package;
import static some.package.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThat;
import org.testng.annotations.Test;

public class ComparableClassTest {
    @Test
    public void basicTest() {
        final ComparableClass a = new ComparableClass("a");
        final ComparableClass b = new ComparableClass("b");

        assertThat(a).hasAttribute("a");
        assertThat(b).hasAttribute("b");

        assertThat(a).isLessThan(b);
    }   
}
```

The error I get:
```
[...]ComparableClassTest.java:[15,22] cannot find symbol
  symbol:   method isLessThan(me.quis.assertj.ComparableClass)
  location: class me.quis.assertj.ComparableClassAssert
```

I would have expected that I can use the `isLessThan` type of assertions just fine.

I know how to work around this issue but I was wondering what the correct solution would be or if I did any mistakes in my set-up.

Workaround:
```
package some.package;
import static some.package.Assertions.assertThat;
import org.assertj.core.api.Assertions;
import org.testng.annotations.Test;

public class ComparableClassTest {
    @Test
    public void basicTest() {
        final ComparableClass a = new ComparableClass("a");
        final ComparableClass b = new ComparableClass("b");

        assertThat(a).hasAttribute("a");
        assertThat(b).hasAttribute("b");

        Assertions.assertThat(a).isLessThan(b);
    }   
}
```

Please find attached an example project ([assertj-comparable.tar.gz](https://github.com/joel-costigliola/assertj-assertions-generator-maven-plugin/files/1011010/assertj-comparable.tar.gz)) that can be compiled with `mvn assertj:generate-assertions test` to reproduce this problem.

**Comment by joel-costigliola** [comment]
Sorry for the late response, I will look at your issue shortly.

**Comment by joel-costigliola** [comment]
You did nothing wrong, to get `isLessThan` assertions out of the box, the generated assertion class must inherit from `AbstractComparableAssert` which is not the case, all classes inherit from `AbstractObjectAssert` (in our latest commits at least).

There is no straightforward solution (except your workaround), the generator needs to me changed so that it detects classes implementing `Comparable` and switch from the parent class to `AbstractComparableAssert`.

**Comment by joel-costigliola** [comment]
Moved this issue in the right project https://github.com/joel-costigliola/assertj-assertions-generator/issues/111

**Comment by wildcart** [comment]
thanks for solving this.

I will update to the newest release and check this ;)
