### ISSUE TITLE
Errors in generated Javadocs

### ISSUE THREAD

**Issue by Chessray** [joel-costigliola/assertj-assertions-generator-maven-plugin#42]
Running Javadoc on the generated classes fails:

> error: unexpected end tag: `</code>`
> [ERROR] `/** Creates a new </code>{@link JUnitSoftAssertions}</code>. */`
> error: unexpected end tag: `</code>`
> [ERROR] `/** Creates a new </code>{@link SoftAssertions}</code>. */`

> warning: nested tag not allowed: `<b>`
> Verifies that the actual Addresses's addresses contains `<b>`only`<b>` the given Address elements and nothing else in whatever order.

The first two exist in every project where these classes are generated (it's the constructor comments). The third one is generated in Assert classes where the actual classes have collection type members.

**Comment by joel-costigliola** [comment]
Thanks for reporting this, will be fixed in the next version

**Comment by joel-costigliola** [comment]
Fixed in https://github.com/joel-costigliola/assertj-assertions-generator/pull/72
