### ISSUE TITLE
custom_assertion_class does not use generateAssertionsInPackage

### ISSUE THREAD

**Issue by mattyb678** [joel-costigliola/assertj-assertions-generator-maven-plugin#49]
if I set the generateAssertionsInPackage option, the generated assertion classes don't use the value set.

ex. 

`<generateAssertionsInPackage>com.example.assertions</generateAssertionsInPackage>`

in the Assertion entry point class, that value is not used

**Comment by joel-costigliola** [comment]
Thanks for reporting this! 
I'm super busy at the moment, I don;t know when I'll have the time to look into this one

**Comment by mattyb678** [comment]
@joel-costigliola No worries! I'll poke around and see if I can put a PR together

**Comment by jgerken** [comment]
At least for me, it works since version 2.1.0. I think this issue can be closed.

**Comment by joel-costigliola** [comment]
@jgerken thanks for the feedback, I'll close this issue but if it hits someone I'll reopen it.
