### ISSUE TITLE
Custom templates not found in multi-module projects

### ISSUE THREAD

**Issue by uhafner** [joel-costigliola/assertj-assertions-generator-maven-plugin#50]
I have a [project](https://github.com/jenkinsci/analysis-core-plugin/blob/3.0/pom.xml#L183) that has the assertion generator configured. If I run mvn test-compile, then the assertions are correctly generated from my template and the test compile succeeds:
```
--- Generator input parameters ---

The following templates will replace the ones provided by AssertJ when generating AssertJ assertions :
- Using custom template for 'assertions entry point class' loaded from src/test/resources/templates/analysis_core_assertions_entry_point_class_template.txt

Generating AssertJ assertions for classes in following packages and subpackages:
- io.jenkins.plugins.analysis.core.model
```
However, if the same project is part of a [multi-module](https://github.com/jenkinsci/analysis-suite-plugin/blob/3.0/pom.xml) build, then the templates are not found: 
```
--- Generator input parameters ---

The following templates will replace the ones provided by AssertJ when generating AssertJ assertions :
- Use default 'assertions entry point class' assertion template as we failed to to read user template from src/test/resources/templates/analysis_core_assertions_entry_point_class_template.txt

Generating AssertJ assertions for classes in following packages and subpackages:
- io.jenkins.plugins.analysis.core.model
```

**Comment by nickstolwijk** [comment]
Did you try to prefix the templatesDirectory with ${project.basedir}?

And I would suggest to not put your templates under src/test/resources as now they are accessible in your tests. I would prefer to put them under src/test/templates.
```
   <plugin>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-assertions-generator-maven-plugin</artifactId>
        ...
        <configuration>
          .....
          <templates>
            <templatesDirectory>${project.basedir}/src/test/templates/</templatesDirectory>
             ...
          </templates>
        </configuration>
      </plugin>
```

**Comment by uhafner** [comment]
Sorry, that did the trick. From the documentation I thought that this prefix is automatically added. Maybe you should update the documentation of the example in the web page.
